repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c 'gofmt -l . | grep . && exit 1 || exit 0'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: go-vet
        name: go vet
        entry: bash -c 'go vet ./...'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: go-test
        name: go test
        entry: bash -c 'go test ./...'
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: go-test-coverage
        name: go_test_coverage_min_75
        entry: >
          bash -c '
          go test ./... -coverprofile=coverage.out &&
          total=$(go tool cover -func=coverage.out | grep total | awk "{print substr(\$3, 1, length(\$3)-1)}") &&
          echo "Total coverage: $total%" &&
          awk -v cov="$total" "BEGIN { if (cov < 75) { print \"Coverage below 75%\"; exit 1 } }"
          '
        language: system
        pass_filenames: false
        stages: [pre-push]